FROM debian:11
RUN apt-get update && apt-get -y install ca-certificates mosquitto
RUN apt-get -y install procps lsof strace less
RUN bash -c 'echo "listener 1883 0.0.0.0\nnallow_anonymous true" > /etc/mosquitto/conf.d/public.conf'
ADD install-leda.sh ./
RUN chmod a+x ./install-leda.sh
RUN ./install-leda.sh
RUN mkdir -p /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.overlayfs
ADD entrypoint.sh ./
RUN chmod a+x ./entrypoint.sh
ENTRYPOINT [ "./entrypoint.sh" ]