# /********************************************************************************
# * Copyright (c) 2023 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/
#

FROM python

WORKDIR /app

COPY dockerfiles/container-metrics/requirements.txt .
RUN pip3 install -r requirements.txt

COPY dockerfiles/container-metrics/ .

EXPOSE 7355
CMD [ "python3", "app.py" ]
