#!/bin/bash
# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/
#
# Starter script for developers who are building the project
# and testing on qemu
#

KAS_CONFIG = "./kas/leda-kirkstone.yaml"
KAS_CMD = "kas shell kas/leda-kirkstone.yaml -c 'runqemu nographic ovmf kvm'"

MACHINE=$(bitbake-getvar --value MACHINE | tail -1)

case $MACHINE in
    "qemux86-64")
      KVM="kvm"
      OVMF="ovmf"
      CHOICES=("All" "Multi-boot (all of below)" "Full" "Full SDV setup with tools" "Minimal" "Only bare minimum runtime" "Rescue" "Only rescue system")
    ;;
    "qemuarm*")
      KVM=""
      OVMF=""
      CHOICES=("All" "SDV Multi-boot (Full, Minimal, Rescue)")
    ;;
    *)
      KVM=""
      OVMF=""
      CHOICES=("All" "SDV Multi-boot (Full, Minimal, Rescue)")
    ;;
esac 

CHOICE=$(DIALOG_TIMEOUT=5 DIALOG_ESC=1 dialog  \
                --backtitle "Eclipse Leda Runtime Emulator" \
                --title "QEMU Runner" \
                --timeout 5 \
                --menu "Choose SDV image variant to boot on ${MACHINE}:" \
                0 0 4 \
                "${CHOICES[@]}" \
                2>&1 >/dev/tty)
RC=$?

dialog --clear

case $RC in
   0) ;;
   1) exit;;
   5) CHOICE="All";;
   *) exit;;
esac

if [ -z $CHOICE ]
then 
    exit 
fi

case "$CHOICE" in
    "All")
        runqemu $OVMF $KVM sdv-image-all
    ;;
    "Full")
        runqemu $KVM sdv-image-full
    ;;
    "Minimal")
        runqemu $KVM sdv-image-minimal
    ;;
    "Rescue")
        runqemu $KVM sdv-image-rescue
    ;;
esac 

