# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: Leda Release (Self-Hosted)

on:
  release:
    types: [published]

jobs:
  call-build:
    name: Build
    if: github.repository_owner == 'SoftwareDefinedVehicle'
    uses: ./.github/workflows/build-selfhosted.yml
    secrets: inherit

  upload-assets:
    name: Upload assets
    if: github.repository_owner == 'SoftwareDefinedVehicle'
    runs-on: self-hosted
    needs: [ call-build ]
    permissions:
      contents: write
    steps:
      - name: Download qemux86_64 archive
        id: download
        uses: actions/download-artifact@v3
        with:
          path: build/
      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: |
            ${{steps.download.outputs.download-path}}/eclipse-leda-qemu-x86_64.tar.xz/eclipse-leda-qemu-x86_64.tar.xz
            ${{steps.download.outputs.download-path}}/eclipse-leda-qemu-arm64.tar.xz/eclipse-leda-qemu-arm64.tar.xz
            ${{steps.download.outputs.download-path}}/eclipse-leda-raspberrypi.tar.xz/eclipse-leda-raspberrypi.tar.xz
            ${{steps.download.outputs.download-path}}/eclipse-leda-spdx-sbom-qemux86_64.tar.gz/eclipse-leda-spdx-sbom-qemux86_64.tar.gz
            ${{steps.download.outputs.download-path}}/eclipse-leda-spdx-sbom-qemuarm64.tar.gz/eclipse-leda-spdx-sbom-qemuarm64.tar.gz
            ${{steps.download.outputs.download-path}}/eclipse-leda-spdx-sbom-raspberrypi4-64.tar.gz/eclipse-leda-spdx-sbom-raspberrypi4-64.tar.gz
            ${{steps.download.outputs.download-path}}/eclipse-leda-sources-qemux86_64.tar.gz/eclipse-leda-sources-qemux86_64.tar.gz
            ${{steps.download.outputs.download-path}}/eclipse-leda-sources-qemuarm64.tar.gz/eclipse-leda-sources-qemuarm64.tar.gz
            ${{steps.download.outputs.download-path}}/eclipse-leda-sources-raspberrypi4-64.tar.gz/eclipse-leda-sources-raspberrypi4-64.tar.gz
