# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: Leda Release

on:
  release:
    types: [published]

jobs:
  call-build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  upload-assets:
    name: Upload assets
    runs-on: ubuntu-22.04
    needs: [ call-build ]
    permissions:
      contents: write
    steps:
      - name: Download qemux86_64 archive
        id: download
        uses: actions/download-artifact@v3
        with:
          path: build/
      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: |
            ${{steps.download.outputs.download-path}}/eclipse-leda-qemu-x86_64.tar.xz/eclipse-leda-qemu-x86_64.tar.xz
            ${{steps.download.outputs.download-path}}/eclipse-leda-qemu-arm64.tar.xz/eclipse-leda-qemu-arm64.tar.xz
            ${{steps.download.outputs.download-path}}/eclipse-leda-raspberrypi.tar.xz/eclipse-leda-raspberrypi.tar.xz
            ${{steps.download.outputs.download-path}}/eclipse-leda-sbom-qemu-x86_64.tar.xz/eclipse-leda-sbom-qemu-x86_64.tar.xz
            ${{steps.download.outputs.download-path}}/eclipse-leda-sbom-qemu-arm64.tar.xz/eclipse-leda-sbom-qemu-arm64.tar.xz
            ${{steps.download.outputs.download-path}}/eclipse-leda-sbom-raspberrypi.tar.xz/eclipse-leda-sbom-raspberrypi.tar.xz
            ${{steps.download.outputs.download-path}}/eclipse-leda-sources-qemu-x86_64.tar.xz/eclipse-leda-sources-qemu-x86_64.tar.xz
            ${{steps.download.outputs.download-path}}/eclipse-leda-sources-qemu-arm64.tar.xz/eclipse-leda-sources-qemu-arm64.tar.xz
            ${{steps.download.outputs.download-path}}/eclipse-leda-sources-raspberrypi.tar.xz/eclipse-leda-sources-raspberrypi.tar.xz
